/** @format */

export const APP_ROUTES = {
  OTHERS: {
    LANDINGPAGE: "/",
    ABOUT: "/about",
    TNC: "/terms&conditions",
    PRIVACY: "/privacypolicy",
  },
  AUTH: {
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    FORGOT_PASSWORD: "/auth/forgot-password",
    OTP: "/auth/otp",
    VERIFY: "/auth/verify",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_2FA: "/auth/verify-2fa",
    GOOGLE_VERIFY: "/auth/google-verify",
  },
  KYC: {
    PERSONAL: "/wallet/kyc/personal-information",
    POA: "/wallet/kyc/poa",
    IDENTITY: "/wallet/kyc/identity",
    PHONEVERIFICATION: "/wallet/kyc/phone-verification",
    BVNVERIFICATION: "/wallet/kyc/bvn-verification",
    LEVEL3VERIFICATION: "/wallet/kyc/level3-verification",
    BECOME_MERCHANT: "/wallet/kyc/become-a-merchant",
  },
  WALLET: {
    HOME: "/wallet",
    DEPOSIT: "/wallet/deposit",
    WITHDRAW: "/wallet/withdrawal",
    TRANSFER: "/wallet/transfer",
    BANK_SELECT: "/wallet/deposit/bank-select",
    TRANSACTION_BREAKDOWN: "/wallet/deposit/transaction-breakdown",
  },
  P2P: {
    HOME: "/p2p",
    MARKETPLACE: "/p2p/market-place",
    EXPRESS: "/p2p/express",
    ORDER_HISTORY: "/p2p/orders",
    MY_ADS: "/p2p/my-ads",
    AD_DETAILS: "/p2p/my-ads/details",
    CREATE_AD: "/p2p/my-ads/create",
    MY_PROFILE: "/p2p/my-profile",
    SELL: "/p2p/market-place/sell",
    BUY: "/p2p/market-place/buy",
    RECEIPT: "/p2p/market-place/receipt",
  },
  SWAP: {
    HOME: "/swap",
  },
  SETTINGS: {
    PROFILE: "/settings",
    SECURITY: "/settings/security",
    PAYMENT: "/settings/payment",
    SUPPORT: "/settings/support",
    CORPORATE: "/settings/payment/corporate",
  },
  DASHBOARD: "/dashboard",
  NOTIFICATION: "/dashboard/notifications",
  AD: "/ad",
  PROFILE: "/profile",
};
