export type AccountLevel = keyof typeof bisats_limit;

export const bisats_limit = {
  level_1: {
    kyc_level: "level_1",
    daily_withdrawal_limit_fiat: 300_000_000,
    fiat_currency: "ngn",
    daily_withdrawal_limit_crypto: 500_000,
    crypto_currency: "usd",
    charge_on_single_withdrawal_fiat: 53.0,
    charge_on_single_withdrawal_crypto: 0,
    max_deposit_per_transaction_fiat: 0,
    charge_on_single_deposit_fiat: 1000,
    charge_on_single_deposit_crypto: 0,
    minimum_fiat_withdrawal: 15_000,
    maximum_fiat_withdrawal: 10_000_000,
    upper_limit_sell_ad: 0,
    lower_limit_sell_ad: 0,
    upper_limit_buy_ad: 0,
    lower_limit_buy_ad: 0,
    maximum_ad_creation_amount: 0,
  },
  level_2: {
    kyc_level: "level_2",
    daily_withdrawal_limit_fiat: 500_000_000,
    fiat_currency: "ngn",
    daily_withdrawal_limit_crypto: 1_000_000,
    crypto_currency: "usd",
    charge_on_single_withdrawal_fiat: 53.0,
    charge_on_single_withdrawal_crypto: 2,
    deposit_per_transaction_fiat: 10_000_000,
    charge_on_single_deposit_fiat: 1000,
    charge_on_single_deposit_crypto: 0,
    minimum_fiat_withdrawal: 15_000,
    maximum_fiat_withdrawal: 10_000_000,
    charge_on_buy_ad: 0.0002,
    charge_on_sell_ad: 0,
    upper_limit_sell_ad: 23_000_000,
    lower_limit_sell_ad: 15_000,
    upper_limit_buy_ad: 1_000_000,
    lower_limit_buy_ad: 15_000,
    maximum_ad_creation_amount: 10_000_000,
    max_deposit_per_transaction_fiat: 10_000_000,
  },
  level_3: {
    kyc_level: "level_3",
    daily_withdrawal_limit_fiat: 30_000_000_000_000,
    fiat_currency: "ngn",
    daily_withdrawal_limit_crypto: 3_000_000,
    crypto_currency: "usd",
    withdrawal_per_transaction_fiat: 20_000_000,
    charge_on_single_withdrawal_fiat: 53.0,
    charge_on_single_withdrawal_crypto: 0,
    deposit_per_transaction_fiat: 100_000_000,
    charge_on_single_deposit_fiat: 1000,
    charge_on_single_deposit_crypto: 0,
    minimum_fiat_withdrawal: 15_000,
    maximum_fiat_withdrawal: 20_000_000,
    charge_on_buy_ad: 0.0002,
    charge_on_sell_ad: 0,
    upper_limit_sell_ad: 23_000_000,
    lower_limit_sell_ad: 1_000_000,
    upper_limit_buy_ad: 23_000_000,
    lower_limit_buy_ad: 1_000_000,
    maximum_ad_creation_amount: 100_000_000,
    max_deposit_per_transaction_fiat: 100_000_000,
  },
};

export const bisats_charges = {
  crypto_buy: 0.0002,
  crypto_sell: 0,
  ad_creation_sell: 0,
};

export const KYC_LEVELS = {
  NONE: 0,
  LEVEL_1: 1,
  LEVEL_2: 2,
  LEVEL_3: 3,
};

export const ACTIONS = {
  DEPOSIT: "deposit",
  SWAP: "swap",
  WITHDRAW: "withdraw",
  DEPOSIT_NGN: "deposit_ngn",
  WITHDRAW_NGN: "withdraw_ngn",
  DEPOSIT_CRYPTO: "deposit_crypto",
  WITHDRAW_CRYPTO: "withdraw_crypto",
  BUY_CRYPTO: "buy_crypto",
  SELL_CRYPTO: "sell_crypto",
  CREATE_AD: "create_ad",
  HIGH_VALUE_TRANSACTION: "high_value_transaction",
  SET_2FA: "set_2fa",
  ADD_BANK: "add_bank",
  ADD_CORPORATE_BANK: "add_corporate_bank",
  P2P_BUY: "p2p_buy",
  P2P_SELL: "p2p_sell",
  TRANSFER: "transfer",
  MAKE_TRANSFER: "make_transfer",
  // Add more actions
};

export const KYC_RULES = {
  [KYC_LEVELS.NONE]: {
    allowedActions: [ACTIONS.SET_2FA],
    requiresKycModal: true,
  },
  [KYC_LEVELS.LEVEL_1]: {
    allowedActions: [
      // ACTIONS.SELL_CRYPTO,
      ACTIONS.BUY_CRYPTO,
      ACTIONS.DEPOSIT_CRYPTO,
      ACTIONS.WITHDRAW_CRYPTO,
      ACTIONS.WITHDRAW_NGN,
      ACTIONS.SET_2FA,
      ACTIONS.WITHDRAW,
      ACTIONS.ADD_BANK,
      ACTIONS.ADD_CORPORATE_BANK,
      ACTIONS.P2P_BUY,
      ACTIONS.P2P_SELL,
      ACTIONS.TRANSFER,
      ACTIONS.MAKE_TRANSFER,
    ],
    limits: {
      transactionAmount: 1000, // $1000 max per transaction
    },
  },
  [KYC_LEVELS.LEVEL_2]: {
    allowedActions: [
      ACTIONS.DEPOSIT_NGN,
      ACTIONS.SWAP,
      ACTIONS.BUY_CRYPTO,
      ACTIONS.WITHDRAW_NGN,
      ACTIONS.SELL_CRYPTO,
      ACTIONS.DEPOSIT_CRYPTO,
      ACTIONS.WITHDRAW_CRYPTO,
      ACTIONS.SET_2FA,
      ACTIONS.DEPOSIT,
      ACTIONS.CREATE_AD,
      ACTIONS.WITHDRAW,
      ACTIONS.ADD_BANK,
      ACTIONS.ADD_CORPORATE_BANK,
      ACTIONS.P2P_BUY,
      ACTIONS.P2P_SELL,
      ACTIONS.TRANSFER,
      ACTIONS.MAKE_TRANSFER,
    ],
    limits: {
      transactionAmount: 10000,
    },
  },
  [KYC_LEVELS.LEVEL_3]: {
    allowedActions: [
      ACTIONS.DEPOSIT_NGN,
      ACTIONS.BUY_CRYPTO,
      ACTIONS.WITHDRAW_NGN,
      ACTIONS.SELL_CRYPTO,
      ACTIONS.DEPOSIT_CRYPTO,
      ACTIONS.WITHDRAW_CRYPTO,
      ACTIONS.SET_2FA,
      ACTIONS.DEPOSIT,
      ACTIONS.SWAP,
      ACTIONS.CREATE_AD,
      ACTIONS.WITHDRAW,
      ACTIONS.ADD_BANK,
      ACTIONS.ADD_CORPORATE_BANK,
      ACTIONS.P2P_BUY,
      ACTIONS.P2P_SELL,
      ACTIONS.TRANSFER,
      ACTIONS.MAKE_TRANSFER,
    ],
    limits: {
      transactionAmount: Infinity,
    },
  },
};

// Define which actions need 2FA
export const ACTIONS_REQUIRING_2FA = [
  ACTIONS.WITHDRAW_NGN,
  ACTIONS.WITHDRAW_CRYPTO,
  ACTIONS.TRANSFER,
  // ACTIONS.SELL_CRYPTO,
  // ACTIONS.DEPOSIT_NGN,
  // ACTIONS.BUY_CRYPTO,
  // ACTIONS.DEPOSIT_CRYPTO,
  // ACTIONS.CREATE_AD,
];
export const ACTIONS_REQUIRING_PIN = [
  ACTIONS.WITHDRAW_NGN,
  ACTIONS.WITHDRAW_CRYPTO,
  ACTIONS.TRANSFER,
];
